@startuml RecordPlayer-System-Context

Title RecordPlayer System Context: Top Level Design

!include Template/C4/C4_Context.puml

LAYOUT_WITH_LEGEND()

!include Template/tupadr3/font-awesome-5/users.puml

Person(User, User, Primary User, "users")
System(Client, "RecordPlayer Client", "The RecordPlayer Client is a Single-Page-Application built with WebAssembly and WebSockets that communicates changes to and from the RecordPlayer Front End in near real time using SignalR.") 
System(Front_End, "RecordPlayer Front End", "The RecordPlayer Front End is a web server that hosts an ASP.Net web site using SignalR for real-time communication between the client and server using a fully bi-directional channel.") 
System(Back_End, "RecordPlayer Server Back End", "The RecordPlayer Back End is a server that hosts a full CQRS framework including an RecordStore stream database, a DocumentStore for entity snapshots, and a ProjectionStore for projected view-models") 

Rel(User, Client, Uses, via Browser)
Rel(Client, Front_End, Commands, "Push comand Records to the Front End.")
Rel_U(Front_End, Client, Events, "Push event Records to the Client.")

Rel(Front_End, Back_End, Commands, "Push comand Records to the Back End.")
Rel_U(Back_End, Front_End, Events, "Push event Records to the Front End.")

@enduml
