@startuml RecordPlayer System Context

Title RecordPlayer System Context: Top Level Design

!include Template/C4/C4_Context.puml
!include Template/tupadr3/dev2/redis_wordmark.puml

LAYOUT_WITH_LEGEND()

!include Template/tupadr3/font-awesome-5/users.puml
Person(User, User, Primary User, "users")


System_Boundary(Front_End, "Front End") {

  !include Template/logos/webassembly.puml
  System(Client, Client, Blazor WebAssembly, "webassembly")
  
  !include Template/logos/websocket.puml
  System(Web, "RecordPlayer Web", SignalR Hub, "websocket")

}

System_Boundary(Back_End, "Back End") {

  !include Template/tupadr3/font-awesome-5/record_vinyl.puml
  System(Api, "RecordPlayer API", SignalR Hub, "record_vinyl")
  
  !include Template/logos/elasticsearch.puml
  System(Log, Log, Record Store Database, "elasticsearch")
  
  !include Template/tupadr3/devicons/msql_server.puml
  System(Projection, Projection, Projected View Models, "msql_server")
  
  !include Template/tupadr3/dev2/mongodb_wordmark.puml
  System(Models, Models, Persisted Model State, "mongodb_wordmark")

}
Rel(User, Client, Uses, via Browser)
Rel(User, Web, "Navigates To", via Browser)
Rel_R(Client, Web, Bi-directional Event Stream, via SignlaR)
Rel_D(Web, Log, Save Records, via Something)
Rel_D(Log, Api, Read Record Subscriptions, via Something)
Rel_U(Projection, Web, Query Viewmodels, via Something)
Rel_U(Api, Projection, Update Projected View Models, via Something)
Rel_R(Models, Api, Query Model State, via Something)
Rel_L(Api, Models, Save Snapshot State of Model Objects, via Something)

@enduml
